# Generated by Django 3.2.15 on 2024-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_tache_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
